Import cryptography
This commit causes the Lambda to fail with:
ImportError: /var/task/cryptography/hazmat/bindings/_constant_time.abi3.so: invalid ELF header